#!/usr/bin/env bash
set -euo pipefail

# files to be executed during each bootstrap stage
# change the order of files if necessary
BS_PRE=("helpers.sh" "platform.sh" "preflight.sh")
BS_SHELL=("shell.sh")
BS_POST=("bin.sh" "vim.sh" "tmux.sh" "macos.sh")
# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

BOLD_RED='\033[1;31m'
BOLD_YELLOW='\033[1;33m'
BOLD_GREEN='\033[1;32m'
RESET='\033[0m'

echo -e "${BOLD_GREEN}Bootstrapping your shell...${RESET}"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo -e "${BOLD_RED}Error: bootstrap directory '$BOOTSTRAP_D' not found${RESET}" >&2
    exit 1
fi

check_files() {
    local bootstrap

    for bootstrap in "$@"; do
        bootstrap="$BOOTSTRAP_D/$bootstrap"
        if [[ ! -r "$bootstrap" || ! -x "$bootstrap" ]]; then
            echo -e "${BOLD_RED}Error: bootstrap '$bootstrap' is not executable or missing${RESET}" >&2
            exit 1
        fi
    done
}

run_stage() {
    local stage="$1"
    local bootstrap
    shift

    echo "----------------------"
    echo -e "${BOLD_YELLOW}Current stage: ${stage}${RESET}"

    for bootstrap in "$@"; do
        bootstrap="$BOOTSTRAP_D/$bootstrap"
        echo ""
        echo "======================"
        echo -e "Executing ${BOLD_YELLOW}'$bootstrap'${RESET}"
        source "$bootstrap"
    done
}

# check if all files are present and executable
check_files "${BS_PRE[@]}" "${BS_SHELL[@]}" "${BS_POST[@]}"

# Ask for the administrator password upfront
echo "Presaving sudo credentials..."
sudo -v

# Keep-alive: update existing `sudo` timestamp until bootstrap script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

_error_trap() {
    local error_code=$?
    local last_command="${BASH_COMMAND}"

    local i=1
    local error_file="${BASH_SOURCE[${i}]}"
    local error_line="${BASH_LINENO[${i}-1]}"

    echo ""
    echo "======================"
    echo -e "${BOLD_RED}BOOTSTRAP ERROR: Command \`$last_command\` failed with exit code $error_code.${RESET}" >&2
    echo -e "${BOLD_RED}  Occurred in: '${error_file}' at line ${error_line}${RESET}" >&2

    exit 1
}
trap _error_trap ERR

run_stage "PRE" "${BS_PRE[@]}"
run_stage "SHELL" "${BS_SHELL[@]}"
run_stage "POST" "${BS_POST[@]}"

echo "-------------------"
echo -e "${BOLD_GREEN}Bootstrap finished!${RESET}"
# repeated login is required
# e.g. $SHELL stays the same even when opening zsh,
# because SHELL is a login shell that was initially set for the user
echo -e "${BOLD_GREEN}Please open a new session for changes to take effect${RESET}"
